name: Relate
version: "1.0"
description: Maintains two-way references between Collection, Pages and Taxonomy fieldtypes
url: https://www.jbrew.co.uk
developer: James Bradley Ross
developer_url: https://www.jbrew.co.uk
